# Generated by Django 5.2.12 on 2026-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="unique_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
