# Generated by Django 5.2.12 on 2026-03-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_complaint_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="unique_id",
            field=models.CharField(
                blank=True, editable=False, max_length=12, null=True, unique=True
            ),
        ),
    ]
